//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DatabaseFirst.NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long Id { get; set; }
        public Nullable<long> UserProfileId { get; set; }
        public Nullable<long> ShopId { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
